systemProp.java.net.useSystemProxies=true
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4

fabric_version=0.116.9+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0

neoforge_version=21.1.172
kotlin_for_forge_version=5.8.0
